### ISSUE TITLE
Protocol error

### ISSUE THREAD

**Issue by syncgw** [spmp/davx5#1]
Hi, 
please check out https://github.com/sabre-io/dav/issues/1153. It is likely you client does not follow protocol specifications and can therefore not sync. with at least SabreDAV.

**Comment by DeepDiver1975** [comment]
dvavx5 lives here https://gitlab.com/bitfireAT/davx5-ose

**Comment by spmp** [comment]
Sorry @syncgw and @syncgw, I will try to make this repo private to avoid such issues.
